### PR TITLE
Centering fix

### PR DESCRIPTION
**Pull request by ShotgunApe**
Centering fix to address issue https://github.com/jbreitenbucher/exampleis/issues/4. Changes have been tested locally and on Overleaf utilizing pdfLaTeX as the compiler. Supports all three font sizes (10pt, 11pt, 12pt).

### CODE REVIEW

**Comment by jbreitenbucher** [comment]
I need to check if students have a way to set margins easily. I think I hard coded them. The class does offer the option to process for two-sided printing which is intended to be bound with a quarter or half inch binding on the left. So that would impact the positioning of content on the cover. If it is two-sided, then stuff would be shifted to the right vs if it is not.

I'm still learning how to test pull requests as I don't use the git CLI much to do things. I tried to do
git fetch origin pull/ID/head
git cherry-pick FETCH_HEAD

and that didn't go so well.

**Comment by jbreitenbucher** [comment]
I was intrigued by your reorganization to have a complete and minimal folder. I assume you intended that a student would use the minimal set to sort of start from scratch?

**Comment by ShotgunApe** [comment]
The intention would be to use the minimal set to start from scratch. I found that testing `\documentclass` for the draft and PDF versions found in the Student/Advisor guidelines produced errors that were from dependencies found in the current default template (I think?). 

Having a clean slate to just drop into Overleaf (without the need of deleting) was something I imagine others may find useful, but is not required since the examples are also quite useful.

image

**Comment by ShotgunApe** [comment]
To address https://github.com/jbreitenbucher/exampleis/pull/5#issuecomment-2334376545 I would need to spend a bit more time to create the logic to change the margins for a two-sided paper. If the current margins are the planned default for students, however, I believe that this could work as a small patch for now since students will probably not be printing their IS until a later date.

**Comment by jbreitenbucher** [comment]
Hmm. I just processed username.tex again and got some warnings about overfull and underfull boxes as well as some reused labels (not sure that is correct), but no errors. So, you are saying if you don't have all of the packages being called in the documentclass then you get unrecoverable errors?

**Comment by jbreitenbucher** [comment]
Is your screenshot from the MCS website? I recall them pointing to something that was not the git repository and that certainly caused issues for folks that tried to use the old version.

**Comment by jbreitenbucher** [comment]
> The intention would be to use the minimal set to start from scratch. I found that testing `\documentclass` for the draft and PDF versions found in the Student/Advisor guidelines produced errors that were from dependencies found in the current default template (I think?).
> 
> Having a clean slate to just drop into Overleaf (without the need of deleting) was something I imagine others may find useful, but is not required since the examples are also quite useful.
> 
> image

I'm not opposed to having a minimal version. Not sure how students would checkout the minimal version. I suppose they could download the project and just delete the complete folder as long as minimal worked. It would also not be necessary to include all the appendices or code examples in a minimal version.

**Pull request merged**
